# Numerical Python (NumPy)

In [1]:
import numpy as np

Creating Array

In [2]:
arr = [11, 12, 13]
n_arr = np.array(arr)

In [3]:
n_arr

array([11, 12, 13])

Just pass in a list directly

In [4]:
n_arr1 = np.array([101, 102, 103])

Pass in a list of lists to create a multidimensional array.

In [5]:
multi_arr = np.array([[11, 123, 1234], [45, 56, 67]])

In [6]:
multi_arr

array([[  11,  123, 1234],
       [  45,   56,   67]])

"shape" method to find the dimensions of the array (rows, columns).

In [7]:
multi_arr.shape

(2, 3)

"arange" returns evenly spaced values within a given interval.

In [8]:
help(np.arange)

Help on built-in function arange in module numpy:

arange(...)
    arange([start,] stop[, step,], dtype=None)
    
    Return evenly spaced values within a given interval.
    
    Values are generated within the half-open interval ``[start, stop)``
    (in other words, the interval including `start` but excluding `stop`).
    For integer arguments the function is equivalent to the Python built-in
    `range` function, but returns an ndarray rather than a list.
    
    When using a non-integer step, such as 0.1, the results will often not
    be consistent.  It is better to use `numpy.linspace` for these cases.
    
    Parameters
    ----------
    start : number, optional
        Start of interval.  The interval includes this value.  The default
        start value is 0.
    stop : number
        End of interval.  The interval does not include this value, except
        in some cases where `step` is not an integer and floating point
        round-off affects the length of `out`.
   

In [13]:
range_arr = np.arange(0, 50, 2)

In [14]:
range_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [18]:
range_arr = range_arr.reshape(5, 5)    # reshape method returns new array.

In [19]:
range_arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [20]:
arr_2 = np.random.randint(0, 99, size=25)

In [21]:
arr_2

array([54, 66, 77, 27, 94, 44,  4, 32, 55, 93, 39, 40, 43, 54, 58, 68, 15,
        0, 79, 39, 66, 90, 33, 31, 96])

In [22]:
arr_2.resize(5, 5)    # resize method changes in place.

In [23]:
arr_2

array([[54, 66, 77, 27, 94],
       [44,  4, 32, 55, 93],
       [39, 40, 43, 54, 58],
       [68, 15,  0, 79, 39],
       [66, 90, 33, 31, 96]])

In [40]:
arr_3 = np.linspace(0, 9, 18)

In [42]:
%precision 2
arr_3

array([0.  , 0.53, 1.06, 1.59, 2.12, 2.65, 3.18, 3.71, 4.24, 4.76, 5.29,
       5.82, 6.35, 6.88, 7.41, 7.94, 8.47, 9.  ])

In [45]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [46]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

'diag' method constracts array with given diagonal or extracts diagonal from array.

In [51]:
arr_4 = np.diag([10, 11, 12])

In [52]:
arr_4

array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [53]:
np.diag(arr_4)

array([10, 11, 12])