# Numerical Python (NumPy)

In [58]:
import numpy as np

Creating Array

In [59]:
arr = [11, 12, 13]
n_arr = np.array(arr)

In [60]:
n_arr

array([11, 12, 13])

In [82]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

Just pass in a list directly

In [61]:
n_arr1 = np.array([101, 102, 103])

Pass in a list of lists to create a multidimensional array.

In [62]:
multi_arr = np.array([[11, 123, 1234], [45, 56, 67]])

In [63]:
multi_arr

array([[  11,  123, 1234],
       [  45,   56,   67]])

"shape" method to find the dimensions of the array (rows, columns).

In [7]:
multi_arr.shape

(2, 3)

In [65]:
multi_arr.ndim # number of dimensions using attribute 'ndim'.

2

In [67]:
multi_arr.dtype.name

'int32'

In [76]:
multi_arr = multi_arr.astype('float')

In [78]:
multi_arr.dtype.name

'float64'

"arange" returns evenly spaced values within a given interval.

In [8]:
range_arr = np.arange(0, 50, 2)

In [9]:
range_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [10]:
range_arr = range_arr.reshape(5, 5)    # reshape method returns new array.

In [11]:
range_arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [12]:
arr_2 = np.random.randint(0, 99, size=25)

In [13]:
arr_2

array([29, 11, 40, 32, 42, 75, 35, 36, 17, 39, 37, 87, 96, 64, 18, 72, 20,
       88, 65,  9, 89, 85, 88, 13, 36])

In [14]:
arr_2.resize(5, 5)    # resize method changes in place.

In [15]:
arr_2

array([[29, 11, 40, 32, 42],
       [75, 35, 36, 17, 39],
       [37, 87, 96, 64, 18],
       [72, 20, 88, 65,  9],
       [89, 85, 88, 13, 36]])

In [16]:
arr_3 = np.linspace(0, 9, 18)

In [17]:
%precision 2
arr_3

array([0.  , 0.53, 1.06, 1.59, 2.12, 2.65, 3.18, 3.71, 4.24, 4.76, 5.29,
       5.82, 6.35, 6.88, 7.41, 7.94, 8.47, 9.  ])

In [18]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [19]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

'diag' method constracts array with given diagonal or extracts diagonal from array.

In [20]:
arr_4 = np.diag([10, 11, 12])

In [21]:
arr_4

array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [22]:
np.diag(arr_4)

array([10, 11, 12])

Create an array using repeated list or np.tile

In [23]:
arr_5 = np.array([1, 2, 3]*3)

In [24]:
arr_5

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [25]:
a = [11, 12, 13]
a = np.tile(a, 3)

In [26]:
a

array([11, 12, 13, 11, 12, 13, 11, 12, 13])

In [27]:
arr_6 = np.random.randint(0, 100, size=(3, 3))

In [28]:
arr_6

array([[60, 89, 59],
       [20, 52, 77],
       [68, 55,  9]])

In [29]:
arr_6 = np.random.randint([10, 100, 1000], [100, 1000, 10000], size=(4, 3))

In [30]:
arr_6


array([[  40,  813, 1233],
       [  18,  616, 5949],
       [  49,  809, 5679],
       [  58,  268, 3931]])

Repeat each element in the array use 'repeat' method.

In [31]:
np.repeat(arr_6, 2)

array([  40,   40,  813,  813, 1233, 1233,   18,   18,  616,  616, 5949,
       5949,   49,   49,  809,  809, 5679, 5679,   58,   58,  268,  268,
       3931, 3931])

In [32]:
p = np.ones((2, 2), int)

Use vstack to stack an array vertically

In [33]:
np.vstack([p, p*2])   # also modify the array by multy by 2

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

Use hstack to stack an array horizontally.

In [34]:
np.hstack([p, p*3])

array([[1, 1, 3, 3],
       [1, 1, 3, 3]])

In [35]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [36]:
a + b

array([5, 7, 9])

In [37]:
a*b

array([ 4, 10, 18])

In [38]:
a.dot(b)   # 1*4 + 2*5 + 3*6

32

In [39]:
c = np.array([b, b**2])

In [40]:
c

array([[ 4,  5,  6],
       [16, 25, 36]])

Transposing an array use 'T' method

In [41]:
c.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

Data type of the elements in the array use dtype

In [42]:
c.dtype

dtype('int32')

Use 'astype' method to cast to a specific data type.

In [43]:
c = c.astype('f')

In [44]:
c

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [45]:
c.sum()

92.0

In [46]:
c.max()

36.0

In [47]:
c.min()

4.0

In [48]:
c.mean()

15.333333

Standart deviation use 'std' method

In [49]:
c.std()

11.855613

In [50]:
c.argmax()   # returns index of the max element in the arrray

5

In [51]:
c.argmin()

0

# Indexing and Slicing

In [52]:
x = np.random.randint(10, 100, size=(5, 5))

In [53]:
x

array([[72, 13, 24, 41, 85],
       [32, 72, 12, 64, 34],
       [27, 83, 29, 56, 76],
       [34, 25, 12, 66, 24],
       [93, 64, 90, 19, 86]])

Use bracket notation to slice: 'array[row, column]'

In [54]:
x[2, 3]

56

In [55]:
x[::2]   # each second row

array([[72, 13, 24, 41, 85],
       [27, 83, 29, 56, 76],
       [93, 64, 90, 19, 86]])

In [56]:
x[::2, ::2]

array([[72, 24, 85],
       [27, 29, 76],
       [93, 90, 86]])

In [57]:
arr_7 = 

SyntaxError: invalid syntax (<ipython-input-57-11f2d31abe7a>, line 1)