# Numerical Python (NumPy)

In [24]:
import numpy as np

Creating Array

In [25]:
arr = [11, 12, 13]
n_arr = np.array(arr)

In [26]:
n_arr

array([11, 12, 13])

Just pass in a list directly

In [27]:
n_arr1 = np.array([101, 102, 103])

Pass in a list of lists to create a multidimensional array.

In [28]:
multi_arr = np.array([[11, 123, 1234], [45, 56, 67]])

In [29]:
multi_arr

array([[  11,  123, 1234],
       [  45,   56,   67]])

"shape" method to find the dimensions of the array (rows, columns).

In [30]:
multi_arr.shape

(2, 3)

"arange" returns evenly spaced values within a given interval.

In [31]:
range_arr = np.arange(0, 50, 2)

In [32]:
range_arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [33]:
range_arr = range_arr.reshape(5, 5)    # reshape method returns new array.

In [34]:
range_arr

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48]])

In [35]:
arr_2 = np.random.randint(0, 99, size=25)

In [36]:
arr_2

array([79, 37, 77, 48, 21,  7, 68, 56, 43, 56, 55, 44, 49, 77, 28, 98, 30,
       40, 92, 78, 70, 13, 54, 16,  1])

In [37]:
arr_2.resize(5, 5)    # resize method changes in place.

In [38]:
arr_2

array([[79, 37, 77, 48, 21],
       [ 7, 68, 56, 43, 56],
       [55, 44, 49, 77, 28],
       [98, 30, 40, 92, 78],
       [70, 13, 54, 16,  1]])

In [39]:
arr_3 = np.linspace(0, 9, 18)

In [40]:
%precision 2
arr_3

array([0.  , 0.53, 1.06, 1.59, 2.12, 2.65, 3.18, 3.71, 4.24, 4.76, 5.29,
       5.82, 6.35, 6.88, 7.41, 7.94, 8.47, 9.  ])

In [41]:
np.ones((3, 2), dtype=int)

array([[1, 1],
       [1, 1],
       [1, 1]])

In [42]:
np.zeros((3, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

'diag' method constracts array with given diagonal or extracts diagonal from array.

In [43]:
arr_4 = np.diag([10, 11, 12])

In [44]:
arr_4

array([[10,  0,  0],
       [ 0, 11,  0],
       [ 0,  0, 12]])

In [45]:
np.diag(arr_4)

array([10, 11, 12])

Create an array using repeated list or np.tile

In [46]:
arr_5 = np.array([1, 2, 3]*3)

In [47]:
arr_5

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [48]:
a = [11, 12, 13]
a = np.tile(a, 3)

In [49]:
a

array([11, 12, 13, 11, 12, 13, 11, 12, 13])

In [52]:
arr_6 = np.random.randint(0, 100, size=(3, 3))

In [53]:
arr_6

array([[79, 10, 17],
       [71, 67, 46],
       [35, 94, 21]])

In [62]:
arr_6 = np.random.randint([10, 100, 1000], [100, 1000, 10000], size=(4, 3))

In [70]:
arr_6


array([[  28,  177, 3754],
       [  26,  969, 8045],
       [  59,  760, 5992],
       [  89,  703, 2266]])

Repeat each element in the array use 'repeat' method.

In [74]:
np.repeat(arr_6, 2)

array([  28,   28,  177,  177, 3754, 3754,   26,   26,  969,  969, 8045,
       8045,   59,   59,  760,  760, 5992, 5992,   89,   89,  703,  703,
       2266, 2266])

In [76]:
p = np.ones((2, 2), int)

Use vstack to stack an array vertically

In [79]:
np.vstack([p, p*2])   # also modify the array by multy by 2

array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

Use hstack to stack an array horizontally.

In [80]:
np.hstack([p, p*3])

array([[1, 1, 3, 3],
       [1, 1, 3, 3]])

In [81]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [82]:
a + b

array([5, 7, 9])

In [83]:
a*b

array([ 4, 10, 18])

In [84]:
a.dot(b)   # 1*4 + 2*5 + 3*6

32

In [87]:
c = np.array([b, b**2])

In [88]:
c

array([[ 4,  5,  6],
       [16, 25, 36]])

Transposing an array use 'T' method

In [89]:
c.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

Data type of the elements in the array use dtype

In [90]:
c.dtype

dtype('int32')

Use 'astype' method to cast to a specific data type.

In [93]:
c = c.astype('f')

In [94]:
c

array([[ 4.,  5.,  6.],
       [16., 25., 36.]], dtype=float32)

In [96]:
c.sum()

92.0

In [97]:
c.max()

36.0

In [98]:
c.min()

4.0

In [99]:
c.mean()

15.333333

Standart deviation use 'std' method

In [100]:
c.std()

11.855613

In [102]:
c.argmax()   # returns index of the max element in the arrray

5

In [103]:
c.argmin()

0

# Indexing and Slicing

In [104]:
x = np.random.randint(10, 100, size=(5, 5))

In [105]:
x

array([[10, 98, 62, 59, 39],
       [65, 26, 41, 42, 55],
       [79, 39, 53, 45, 21],
       [71, 98, 12, 39, 13],
       [57, 35, 24, 52, 39]])

Use bracket notation to slice: 'array[row, column]'

In [106]:
x[2, 3]

45

In [108]:
x[::2]   # each second row

array([[10, 98, 62, 59, 39],
       [79, 39, 53, 45, 21],
       [57, 35, 24, 52, 39]])

In [109]:
x[::2, ::2]

array([[10, 62, 39],
       [79, 53, 21],
       [57, 24, 39]])